# Generated by Django 2.2.2 on 2019-11-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191102_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default='products/images/default.gif', upload_to='products/images/'),
        ),
    ]
